version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: yosuke
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    restart: always
    networks:
      - test
networks:
  test: